#!/bin/sh
#################################################################
#                       GENERAL SETTINGS                        #
#################################################################
# gcc compiler
alias ggc='gcc -Wall -Wextra -Werror'

# git bare dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# ls colors and aliases
alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
alias ll='ls -l'
alias la='ls -la'
alias lA='ls -A'
alias l='ls -CF'

# Vim
alias v='nvim'

# networking
alias ip='ip -c'

# dir colors
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
# grep colors
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#################################################################
#                       APPLICATION LAYER                       #
#################################################################
# ffplay Music and Video Player
alias mp='for f in *.mp3 ; do ffplay -nodisp -autoexit "$f"; done'
# open emacs in terminal mode
alias emacs='emacs -nw'

