#!/bin/sh
#################################################################
#			ENVAIRONMENT VARIABLES			#
#################################################################
# Ensure XDG_RUNTIME_DIR is set
unset XDG_RUNTIME_DIR
export XDG_RUNTIME_DIR=$(mktemp -d /tmp/$(id -u)-runtime-dir.XXX)

# random color script
#colorscript random

# Starship if not installed via Cargo.
eval "$(starship init bash)"


