#!/bin/sh
#################################################################
#			GENERAL SETTINGS			#
#################################################################
# Wayland platform by default
export QT_QPA_PLATFORM=wayland
export QT_STYLE_OVERRIDE=adwaita-dark

# Golang
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Rust Lang
export PATH="$HOME/.cargo/bin:$PATH"

# Python pip
export PATH=$PATH:$HOME/.local/bin
# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"

# ziglang
export PATH="$HOME/.zig:$PATH"

#################################################################
#			APPLICATION LAYER			#
#################################################################
# Doom Emacs
export PATH=$PATH:$HOME/.config/emacs/bin

# Starship config
export STARSHIP_CONFIG=~/.config/starship/conf.d/starship.toml

# Android Studio
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
  
# Flutter 
export PATH="/opt/flutter/bin:$PATH"
export PATH="$PATH:`pwd`/flutter/bin"

