#!/bin/sh
#################################################################
#			GENERAL SETTINGS			#
#################################################################
# Wayland platform by default
export QT_QPA_PLATFORM=wayland
export QT_STYLE_OVERRIDE=adwaita-dark

# Golang
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Rust Lang
export PATH="$HOME/.cargo/bin:$PATH"

# Python pip
export PATH=$PATH:$HOME/.local/bin
# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"

# ziglang
export PATH="$HOME/.zig:$PATH"

#################################################################
#			APPLICATION LAYER			#
#################################################################
# Doom Emacs
export PATH=$PATH:$HOME/.config/emacs/bin

# Starship config
export STARSHIP_CONFIG=~/.config/starship/conf.d/starship.toml
