#!/bin/sh
#################################################################
#                       VARIABLES			 	#
#################################################################
CONFIG_DIR=$HOME/.config/shells/conf.d
ALIASES=$CONFIG_DIR/aliases
ENVAR=$CONFIG_DIR/envar
PATHES=$CONFIG_DIR/pathes

#################################################################
#			BASHRC DEFAULT				#
#################################################################
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

#################################################################
#			USER PREFERENCE				#
#################################################################
# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# Enable color support of ls.
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Custom Confugration Directory
if [ -n "$CONFIG_DIR" ]; then
	# Aliases
	if [ -f $ALIASES ]; then
		. $ALIASES
	fi

	# Enaironment Variables
	if [ -f $ENVAR ]; then
    		. $ENVAR
	fi
fi

# emacs gitignore
function gi { curl https://www.toptal.com/developers/gitignore/api/"$(IFS=, ; echo "$*")"; }


